/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */


package domain.src.main.java.fr.uga.miage.m1.reactorexample.exception.data;

/**
 * Data exception  for the entity Parking.
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */

public class ParkingEntityNotFoundException extends Exception {

    public ParkingEntityNotFoundException(String message) {
        super(message);
    }

}

