/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package domain.src.main.java.fr.uga.miage.m1.reactorexample.service;



import fr.uga.miage.m1.reactorexample.api.AdminServicePort;
import fr.uga.miage.m1.reactorexample.exception.data.AdminEntityAlreadyExist;
import fr.uga.miage.m1.reactorexample.exception.data.AdminEntityNotFoundException;
import fr.uga.miage.m1.reactorexample.exception.domain.AdminCreationException;
import fr.uga.miage.m1.reactorexample.exception.domain.AdminNotFoundException;
import fr.uga.miage.m1.reactorexample.models.Admin;
import fr.uga.miage.m1.reactorexample.models.AdminToCreate;
import fr.uga.miage.m1.reactorexample.port.AdminDataPort;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;

/**
 * Service for entity "Admin" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys & kakaprout for m1miage2025
 *
 */

@Service
@RequiredArgsConstructor
public class AdminService implements AdminServicePort {
    private final AdminDataPort adminDataPort;

    @Override
    public Mono<Admin> create(AdminToCreate adminToCreate) {
        return adminDataPort.createAdmin(adminToCreate)
                .onErrorMap(AdminEntityAlreadyExist.class, ex -> new AdminCreationException(ex.getMessage()))
                .flatMap(Mono::just);
    }

        @Override
    public Mono<Admin> getAdmin(String email) {
        return adminDataPort.findById(email)
                .onErrorMap(AdminEntityNotFoundException.class, ex -> new AdminNotFoundException(ex.getMessage()));
    }
    
    @Override
    public Flux<Admin> getAll() {
        return adminDataPort.findAll();
    }
}

