/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */


package rest_api.src.main.java.fr.uga.miage.m1.reactorexample.request;

import lombok.Data;

import java.math.BigDecimal;

/**
 * DTO to create request for the entity Admin.
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */

@Data
public class AdminToCreateRequest {
        String email;
        String motdepass;
        String nom;
        String prenom;
        BigDecimal telephone;
        String idparking;
    }
