/*
 * Created on 2025-01-30 ( 11:28:41 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package data.src.main.java.fr.uga.miage.m1.reactorexample.data.repositories;


import com.htech.data.jpa.reactive.repository.ReactiveJpaRepository;
import fr.uga.miage.m1.reactorexample.data.models.AdminEntity;
import jakarta.persistence.LockModeType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Lock;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;


import java.math.BigDecimal;


/**
 * Reactive JPA repository for entity "Admin" <br> 
 * 
 * @author Telosys & kakaprout for m1miage2025
 *
 */


@Repository
public interface AdminRepository extends ReactiveJpaRepository<AdminEntity, String> {

    @Override
    @Lock(LockModeType.READ)
    Flux<AdminEntity> findAll();

        Mono<Boolean> existsBy
            Email    (
            String email    );
	
    Mono<Page<AdminEntity>> findAll(Pageable pageable);

	    Mono<AdminEntity> findById(String id);
    }

