/*
 * Created on 2025-01-30 ( 11:28:41 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package data.src.main.java.fr.uga.miage.m1.reactorexample.data.models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Admin"
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */


@Getter
@SuperBuilder
@RequiredArgsConstructor
@AllArgsConstructor
@Entity
@Table(name="ADMIN", schema="OLOUKPOA" )
public class AdminEntity {

    //--- PRIMARY KEY 
    @Id
    @Column(name="EMAIL", nullable=false, length=50)
    private String     email ;

    //--- OTHER DATA FIELDS 
    @Column(name="MOTDEPASS", nullable=false, length=50)
    private String     motdepass ;

    @Column(name="NOM", nullable=false, length=50)
    private String     nom ;

    @Column(name="PRENOM", nullable=false, length=50)
    private String     prenom ;

    @Column(name="TELEPHONE", nullable=false)
    private BigDecimal telephone ;

    @Column(name="IDPARKING", nullable=false, length=15)
    private String     idparking ;


    //--- LINKS ( RELATIONSHIPS )
            @ManyToOne
    @JoinColumn(name="IDPARKING", referencedColumnName="IDPARKING", insertable=false, updatable=false)

            private Parking   Entity parking ;



}
