/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package data.src.main.java.fr.uga.miage.m1.reactorexample.data.models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.math.BigDecimal;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Parking"
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */


@Getter
@SuperBuilder
@RequiredArgsConstructor
@AllArgsConstructor
@Entity
@Table(name="PARKING", schema="OLOUKPOA" )
public class ParkingEntity {

    //--- PRIMARY KEY 
    @Id
    @Column(name="IDPARKING", nullable=false, length=15)
    private String     idparking ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOM", length=100)
    private String     nom ;

    @Column(name="TYPEPARKING", length=50)
    private String     typeparking ;

    @Column(name="URL", length=255)
    private String     url ;

    @Column(name="NOMBREDEPLACE")
    private BigDecimal nombredeplace ;

    @Column(name="ADRESSE", length=255)
    private String     adresse ;

    @Column(name="HAUTEURMAX")
    private BigDecimal hauteurmax ;

    @Column(name="NUMSIRET", length=14)
    private String     numsiret ;

    @Column(name="XLONG")
    private BigDecimal xlong ;

    @Column(name="YLAT")
    private BigDecimal ylat ;

    @Column(name="TARIF1H")
    private BigDecimal tarif1h ;

    @Column(name="TARIF2H")
    private BigDecimal tarif2h ;

    @Column(name="TARIF3H")
    private BigDecimal tarif3h ;

    @Column(name="TARIF4H")
    private BigDecimal tarif4h ;

    @Column(name="TARIF24H")
    private BigDecimal tarif24h ;

    @Column(name="CODEINSEE", length=50)
    private String     codeinsee ;


    //--- LINKS ( RELATIONSHIPS )
            @OneToMany(mappedBy="parking")

            private List<Admin>Entity listOfAdmin ;

            @OneToMany(mappedBy="parking")

            private List<Place>Entity listOfPlace ;

            @ManyToOne
    @JoinColumn(name="CODEINSEE", referencedColumnName="CODEINSEE", insertable=false, updatable=false)

            private City      Entity city ;



}
