/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package rest_api.src.main.java.fr.uga.miage.m1.reactorexample.response;

import java.math.BigDecimal;

/**
 * DTO class for "Admin"
 *
 * @author Telosys and & kakaprout for m1miage2025
 *
 */

public record AdminDTO (
            String email,		
            String motdepass,		
            String nom,		
            String prenom,		
            BigDecimal telephone,		
            String idparking		
    ) {}
