/*
 * Created on 2025-01-30 ( 11:28:43 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */


package entrypoint.src.main.java.fr.uga.miage.m1.entrypoint;

import fr.uga.miage.m1.reactorexample.models.Parking;
import fr.uga.miage.m1.reactorexample.models.ParkingToCreate;
import fr.uga.miage.m1.reactorexample.request.ParkingToCreateRequest;
import fr.uga.miage.m1.reactorexample.response.ParkingDTO;
import org.mapstruct.Mapper;

/**
 * Mapper for the Parking.
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */

@Mapper
public interface ParkingMapper {

    ParkingDTO toParkingResponse(Parking parking);

    ParkingToCreate toParkingToCreate(ParkingToCreateRequest parkingToCreateRequest);
}
