/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package domain.src.main.java.fr.uga.miage.m1.reactorexample.port;


import fr.uga.miage.m1.reactorexample.models.Admin;
import fr.uga.miage.m1.reactorexample.models.AdminToCreate;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;

/**
 * Data port for entity "Admin" <br> 
 * 
 * @author Telosys & kakaprout for m1miage2025
 *
 */

public interface AdminDataPort {

    Mono<Admin> createAdmin(AdminToCreate adminToCreate);

        Mono<Admin> findById(String id);
    
    Flux<Admin> findAll();
}