/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package domain.src.main.java.fr.uga.miage.m1.reactorexample.port;


import fr.uga.miage.m1.reactorexample.models.Parking;
import fr.uga.miage.m1.reactorexample.models.ParkingToCreate;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;
import java.util.List;

/**
 * Data port for entity "Parking" <br> 
 * 
 * @author Telosys & kakaprout for m1miage2025
 *
 */

public interface ParkingDataPort {

    Mono<Parking> createParking(ParkingToCreate parkingToCreate);

        Mono<Parking> findById(String id);
    
    Flux<Parking> findAll();
}