/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */


package data.src.main.java.fr.uga.miage.m1.reactorexample.data.mapper;

import fr.uga.miage.m1.reactorexample.data.models.AdminEntity;
import fr.uga.miage.m1.reactorexample.models.Admin;
import org.mapstruct.Mapper;

/**
 * Mapper for the entity Admin.
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */

@Mapper
public interface AdminEntityMapper {

    AdminEntity toAdminEntity(Admin admin);

    Admin toAdmin(AdminEntity adminEntity);
}
