/*
 * Created on 2025-01-30 ( 11:28:42 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package domain.src.main.java.fr.uga.miage.m1.reactorexample.models;

import lombok.Data;

import java.math.BigDecimal;
import java.util.List;

/**
 * Record to create for the entity Parking.
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */

@Data
public class ParkingToCreate {
        String idparking;
        String nom;
        String typeparking;
        String url;
        BigDecimal nombredeplace;
        String adresse;
        BigDecimal hauteurmax;
        String numsiret;
        BigDecimal xlong;
        BigDecimal ylat;
        BigDecimal tarif1h;
        BigDecimal tarif2h;
        BigDecimal tarif3h;
        BigDecimal tarif4h;
        BigDecimal tarif24h;
        String codeinsee;
}