/*
 * Created on 2025-01-30 ( 11:28:43 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package entrypoint.src.main.java.fr.uga.miage.m1.controller;



import fr.uga.miage.m1.reactorexample.api.ParkingServicePort;
import fr.uga.miage.m1.reactorexample.endpoint.ParkingEndpoints;
import fr.uga.miage.m1.entrypoint.mapper.ParkingMapper;
import fr.uga.miage.m1.reactorexample.request.ParkingToCreateRequest;
import fr.uga.miage.m1.reactorexample.response.ParkingDTO;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;
import java.util.List;

/**
 * RestController for the entity Parking.
 *
 * @author Telosys & kakaprout for m1miage2025
 *
 */

@RestController
@RequiredArgsConstructor
public class ParkingController implements ParkingEndpoints {
    private final ParkingServicePort parkingServicePort;
    private final ParkingMapper parkingMapper;

    @Override
    @ResponseStatus(HttpStatus.CREATED)
    @PostMapping
    public Mono<ParkingDTO> addParking(@RequestBody ParkingToCreateRequest parkingToCreateRequest) {
        return parkingServicePort.create(parkingMapper.toParkingToCreate(parkingToCreateRequest))
                .map(parkingMapper::toParkingResponse);
    }

	    @Override
    @ResponseStatus(HttpStatus.OK)
    @GetMapping("/{id}")
    public Mono<ParkingDTO> getParking(@PathVariable String id) {
        return parkingServicePort.getParking(id)
                .map(parkingMapper::toParkingResponse);
    }
    
    @Override
    @GetMapping("/all")
    public Flux<ParkingDTO> getAllParkings() {
        return parkingServicePort.getAll()
                .map(parkingMapper::toParkingResponse);
    }
}
